### ISSUE TITLE
Switch compiler to ee-gcc

### ISSUE THREAD

**Issue by TheOnlyZac** [TheOnlyZac/sly1#34]
To eventually produce a matching decomp we need to switch the compiler to the ee-gcc (archived [here](https://archive.org/download/SNSystemsProDGPs2/ProDGPs2usrLocalSceFiles.zip)). That means reformatting the code to follow to the older C++ standard.

## Tasks

- [x] Refactor code as C++98
- [x] Add/update Makefiles
- [x] Write instructions for using the new compiler
